version: "3.8"
services:
  mongo:
    image: mongo
    container_name: db_container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
    networks:
      - foodie-net  # Attache le service mongo au réseau

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    environment:
      NODE_ENV: ${NODE_ENV}
      NODE_PORT: ${NODE_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    command: npm run dev  # Utilise nodemon pour le développement
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # Monte le répertoire courant dans le conteneur
    networks:
      - foodie-net   # Attache le service app au réseau
volumes:
  mongo_data:

networks:
  foodie-net:  # Déclare le réseau foodie-net